name: kode_view
description: Flutter syntax highlighting widgets based on Highlights
version: 0.0.1
homepage: https://github.com/SnipMeDev/kode_view

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
