name: kode_view
publish_to: none
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/SnipMeDev/kode_view

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.6"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  highlights_plugin:
    git:
      url: https://github.com/SnipMeDev/highlights_plugin.git
      ref: release/0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.snipme.kode_view
        pluginClass: KodeViewPlugin
      ios:
        pluginClass: KodeViewPlugin
      linux:
        pluginClass: KodeViewPlugin
      macos:
        pluginClass: KodeViewPlugin
      windows:
        pluginClass: KodeViewPluginCApi
